import { NextRequest, NextResponse } from 'next/server';
import { SimpleMongoDBService } from '@/lib/simple-mongodb-service';

// GET - Fetch all approved comments
export async function GET() {
  try {
    console.log('[COMMENTS-GET] Starting to fetch comments...');
    
    const comments = await SimpleMongoDBService.getComments();
    
    console.log(`[COMMENTS-GET] ✅ Fetched ${comments.length} approved comments from MongoDB`);
    
    return NextResponse.json({
      success: true,
      comments: comments,
      count: comments.length,
      database: 'MongoDB',
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('[COMMENTS-GET] ❌ Failed to get comments:', error);
    
    const errorInfo = {
      message: error instanceof Error ? error.message : 'Unknown error',
      name: error instanceof Error ? error.name : 'UnknownError',
      hasMongoUri: !!process.env.MONGODB_URI,
      mongoUriPreview: process.env.MONGODB_URI ? 
        process.env.MONGODB_URI.substring(0, 20) + '...' : 'NOT_SET'
    };
    
    console.error('[COMMENTS-GET] Error details:', errorInfo);
    
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to retrieve comments',
        message: error instanceof Error ? error.message : 'Unknown error',
        debug: errorInfo
      },
      { status: 500 }
    );
  }
}

// POST - Add new comment
export async function POST(request: NextRequest) {
  try {
    console.log('[COMMENTS-POST] Starting comment submission...');
    
    const body = await request.json();
    const { userName, content, episodeViewing } = body;

    console.log(`[COMMENTS-POST] Data received: user=${userName}, content length=${content?.length}, episode=${episodeViewing}`);

    // Get client info
    const userAgent = request.headers.get('user-agent') || '';
    const forwardedFor = request.headers.get('x-forwarded-for');
    const realIp = request.headers.get('x-real-ip');
    const ipAddress = forwardedFor?.split(',')[0] || realIp || 'localhost';

    console.log('[COMMENTS-POST] Attempting to save comment to database...');

    // Add comment using unified service
    const savedComment = await SimpleMongoDBService.addComment({
      id: '', // Will be generated by MongoDB
      userName,
      content,
      timestamp: new Date(),
      isApproved: false,
      userAgent,
      ipAddress,
      episodeViewing
    });

    console.log(`[COMMENTS-POST] ✅ New comment added to MongoDB: ${savedComment._id}`);

    return NextResponse.json({
      success: true,
      comment: savedComment,
      database: 'MongoDB',
      message: 'Comment submitted successfully and pending approval'
    });
  } catch (error) {
    console.error('[COMMENTS-POST] ❌ Failed to add comment:', error);
    
    // Enhanced error handling with Vietnamese messages
    let errorMessage = 'Có lỗi xảy ra khi gửi bình luận';
    let isValidation = false;
    let statusCode = 500;
    
    if (error instanceof Error) {
      const errorMsg = error.message;
      console.error(`[COMMENTS-POST] Error details: ${errorMsg}`);
      
      // Check for validation errors
      if (errorMsg.includes('không được để trống') || 
          errorMsg.includes('quá dài') || 
          errorMsg.includes('spam') ||
          errorMsg.includes('Missing required fields')) {
        isValidation = true;
        errorMessage = errorMsg;
        statusCode = 400;
      }
      // Check for database connection errors
      else if (errorMsg.includes('connection') || 
               errorMsg.includes('timeout') || 
               errorMsg.includes('network') ||
               errorMsg.includes('MongoDB') ||
               errorMsg.includes('MONGODB_URI')) {
        errorMessage = 'Đang có sự cố kết nối cơ sở dữ liệu. Vui lòng thử lại sau.';
        statusCode = 503;
        console.error('[COMMENTS-POST] Database connection error detected');
      }
      // Check for rate limiting or overload
      else if (errorMsg.includes('too many') || 
               errorMsg.includes('rate limit') ||
               errorMsg.includes('overload')) {
        errorMessage = 'Hệ thống đang quá tải. Vui lòng thử lại sau ít phút.';
        statusCode = 429;
      }
      // Check for duplicate errors
      else if (errorMsg.includes('duplicate') || errorMsg.includes('E11000')) {
        errorMessage = 'Bình luận này đã tồn tại. Vui lòng thử lại.';
        statusCode = 409;
      }
      else {
        errorMessage = `Lỗi hệ thống: ${errorMsg}`;
        console.error(`[COMMENTS-POST] Unhandled error type: ${errorMsg}`);
      }
    }
    
    return NextResponse.json(
      { 
        success: false,
        error: 'Failed to add comment',
        message: errorMessage,
        isValidation: isValidation,
        database: 'MongoDB',
        timestamp: new Date().toISOString(),
        // Include retry suggestion for connection errors
        canRetry: statusCode === 503 || statusCode === 429,
        debug: {
          hasMongoUri: !!process.env.MONGODB_URI,
          mongoUriLength: process.env.MONGODB_URI?.length || 0,
          errorType: error instanceof Error ? error.name : 'Unknown'
        }
      },
      { status: statusCode }
    );
  }
}
